config/routes.rb
SkiApp::Application.routes.draw do

  get "home/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :admins, only: [:index], as: 'admins'

  resources :home, only: [:index], as: '/' do
    get 'page/:page', action: :index, on: :collection
  end

  post '/rate' => 'rater#create', :as => 'rate'
  get '/resorts/location', to: "resorts#location", as: :resort_location
  get '/resort/:id/like', to: "resorts#like", as: :resort_like
  get '/resort/:id/unlike', to: "resorts#unlike", as: :resort_unlike
  get '/resorts/search_resorts', to: "resorts#search_resorts", as: :search_resorts

  resources :resorts do
    get 'page/:page', action: :index, on: :collection
    resources :comments do
      member do
        get 'inappropriate'
        delete 'delete_inappropriate', as: :delete_inappropriate
      end
    end
  end

  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end

  root to: "home#index"

  

end

app/views/admins/_flaggings.html.haml
%h1 
  flagged
  %span.magenta> items.

%table
  %tr
    %th Type
    %th Flagged Comment Resort
    %th Flagger
    %th Moderation
  - @flagged_comments.each do |flag|
    - flagged_comment = Comment.find(flag.flaggable_id)
    - flagged_by = User.find(flag.flagger_id)
    %tr
      %td
        = flag.flag.upcase
      %td
        = link_to flagged_comment.resort.name, resort_path(flagged_comment.resort)
      %td
        = link_to flagged_by.name, user_profile_path(flagged_by)
      %td
        = link_to('Delete Comment', [flagged_comment.resort, flagged_comment], :method => :delete, :confirm => 'Are you sure?')

app/views/admins/_users.html.haml
%h1 
  all
  %span.magenta> users.

%table
  %tr
    %th Name
    %th E-Mail
    %th Reviews
    %th Moderation
  - @users.each do |user|
    %tr
      %td= link_to user.name, user_profile_path(user)
      %td= user.email
      %td= user.comments.count
      %td= link_to "Delete User", user, method: :delete, data: { confirm: "Are you sure?" }, method: :delete

app/views/admins/index.html.haml
#admin_panel
  - if current_user.role == "admin"
    = render 'users'

    = render 'flaggings'

  - else
    .notice
      %p Sorry, you are not authorised to view the Admin Panel!