config/routes.rb
SkiApp::Application.routes.draw do

  get "home/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :admins, only: [:index], as: 'admins'

  resources :home, only: [:index], as: '/' do
    get 'page/:page', action: :index, on: :collection
  end

  post '/rate' => 'rater#create', :as => 'rate'
  get '/resorts/location', to: "resorts#location", as: :resort_location
  get '/resort/:id/like', to: "resorts#like", as: :resort_like
  get '/resort/:id/unlike', to: "resorts#unlike", as: :resort_unlike
  get '/resorts/search_resorts', to: "resorts#search_resorts", as: :search_resorts

  resources :resorts do
    get 'page/:page', action: :index, on: :collection
    resources :comments do
      member do
        get 'inappropriate'
        delete 'delete_inappropriate', as: :delete_inappropriate
      end
    end
  end

  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end

  root to: "home#index"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  belongs_to :commentable, :polymorphic => true

  attr_accessible :title, :comment, :user_id, :commentable_type, :flaggable, :flagger, :flag

  default_scope :order => 'created_at ASC'

  
  acts_as_votable
  make_flaggable :inappropriate

  belongs_to :user

  def resort
    commentable
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  before_filter :load_resort

  def create 
    if params[:comment][:commentable_type] == "Resort"
      @comment = @resort.comments.build(params[:comment])

      if @comment.save
        redirect_to resort_path(@resort)
      end
    end
  end

  def load_resort
    @resort = Resort.find(params[:resort_id])
  end

  def inappropriate
    @comment = Comment.find(params[:id])
    current_user.flag(@comment, :inappropriate)
    redirect_to :back, notice: "You have reported this comment."
  end

  def delete_inappropriate
    @comment = Comment.find(params[:id])
    @comment.flaggings.destroy_all
    redirect_to admin_index_path, notice: "You have removed the flag."
  end

  def destroy
    @comment = @resort.comments.find(params[:id])
    @comment.destroy
    redirect_to(@resort)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#single_comment_display
  .pure-g
    .pure-u-1-4
      %a{href: user_profile_path(comment.user)}
        %p
          = comment.user.name
      %a{href: user_profile_path(comment.user)}
        - if comment.user.profile.profile_picture.icon
          %img{src: comment.user.profile.profile_picture.icon}
    .pure-u-3-4
      %p= comment.comment
      - if comment.user != current_user
        - if comment.flagged?
          = image_tag(asset_path('flag_gre.png'))
        -else
          = link_to image_tag(asset_path('flag-gre2.png')), inappropriate_resort_comment_path(Resort.find(params[:id]), comment)
      - else
        = link_to('Delete', [comment.resort, comment], :method => :delete, :confirm => 'Are you sure?')
    