config/routes.rb
SkiApp::Application.routes.draw do

  get "home/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :admins, only: [:index], as: 'admins'

  resources :home, only: [:index], as: '/' do
    get 'page/:page', action: :index, on: :collection
  end

  post '/rate' => 'rater#create', :as => 'rate'
  get '/resorts/location', to: "resorts#location", as: :resort_location
  get '/resort/:id/like', to: "resorts#like", as: :resort_like
  get '/resort/:id/unlike', to: "resorts#unlike", as: :resort_unlike
  get '/resorts/search_resorts', to: "resorts#search_resorts", as: :search_resorts

  resources :resorts do
    get 'page/:page', action: :index, on: :collection
    resources :comments do
      member do
        get 'inappropriate'
        delete 'delete_inappropriate', as: :delete_inappropriate
      end
    end
  end

  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end

  root to: "home#index"

  

end

app/models/resort.rb
class Resort < ActiveRecord::Base
  attr_accessible :area, :area_id, :button_max_temp_fahrenheit, :button_min_temp_fahrenheit, :top_max_temp_fahrenheit, :top_min_temp_fahrenheit, :button_max_temp, :button_min_temp, :top_max_temp, :top_min_temp, :chance_of_snow, :total_snow_fall, :avalanche_warning, :country, :daily_pass_adults, :daily_pass_kids, :day_max_temp, :day_min_temp, :day_weather_description, :forecast_date, :image, :lift_status, :map, :name, :night_grooming, :night_max_temp, :night_min_temp, :night_weather_description, :region, :resort_status, :resort_type, :six_days_pass_adults, :six_days_pass_kids, :snow_last_48hours, :surface_conditions, :weather_forecast, :website, :latitude, :longitude, :lift_count, :run_count, :day_zero_day_title, :day_zero_day_text, :day_one_day_title, :day_one_day_text, :day_two_day_title, :day_two_day_text, :day_three_day_title, :day_three_day_text, :day_four_day_title, :day_four_day_text, :day_five_day_title, :day_five_day_text, :day_six_day_title, :day_six_day_text, :day_seven_day_title, :day_seven_day_text, :day_zero_night_title, :day_zero_night_text, :day_one_night_title, :day_one_night_text, :day_two_night_title, :day_two_night_text, :day_three_night_title, :day_three_night_text, :day_four_night_title, :day_four_night_text, :day_five_night_title, :day_five_night_text, :day_six_night_title, :day_six_night_text, :icon_day_zero, :icon_day_one, :icon_day_two, :icon_day_three, :icon_day_four, :icon_day_five, :icon_day_six, :icon_night_zero, :icon_night_one, :icon_night_two, :icon_night_three, :icon_night_four, :icon_night_five, :icon_night_six, :region_requested

  acts_as_votable
  acts_as_commentable
  letsrate_rateable "resort"

  has_many :resort_relationships
  has_many :instructors, through: :resort_relationships
 
  validates :area_id, uniqueness: true
  validates :name, uniqueness: true

  geocoded_by :area

  def self.find_or_update(id)
    resort = self.find_by_id(id)
    if resort 
      if resort.requested
        resort
      else 
        resort.search_skiarea
        resort
      end
    else
      nil
    end
  end

  def self.find_or_update_region(id)
    resort = self.find_by_id(id)
    if resort 
      if resort.region_requested
        resort
      else 
        resort.search_region
        resort
      end
    else
      nil
    end
  end

  def self.request_weather(id)
    resort = self.find_by_id(id)
    if resort 
      # if resort.updated_within_24_hours?
      #   resort
      # else
        resort.request_weather_data
        resort.request_weather_forecast
        resort
      # end
    else
      nil
    end
  end

  def search_skiarea
    url = "http://www.skimap.org/SkiAreas/view/#{area_id}.json"
    response = HTTParty.get(url)
  
    self.website = response['official_website'] rescue nil
    self.latitude = response['latitude'] rescue nil
    self.longitude = response['longitude'] rescue nil
    self.lift_count = response['lift_count'] rescue nil
    self.run_count = response['run_count'] rescue nil
    
    skimap_code = response['ski_maps'].first['id']
    map_url = "http://www.skimap.org/SkiMaps/view/#{skimap_code}.xml"
    map_response = HTTParty.get(map_url)
    self.map = map_response['skiMap']['thumbnail'].last['url']

    self.requested = true

    save
  end

  def search_region
    url = "http://skimap.org/SkiAreas/view/#{area_id}.json"
    response = HTTParty.get(url)

    self.region = response["regions"].first["name"]

    self.region_requested = true

    save
  end

  def request_weather_data
    url = "http://api.worldweatheronline.com/free/v1/ski.ashx?q=#{latitude}%2C#{longitude}&format=json&key=1eda0e7c99efe8aa8d7440eb652805adf4cd0e2b"
    response = HTTParty.get(url)

    weather = response['data']['weather']
    temperature_bottom = weather.first['bottom']
    self.button_max_temp = temperature_bottom.first['maxtempC']
    self.button_min_temp = temperature_bottom.first['mintempC']
    self.button_max_temp_fahrenheit = temperature_bottom.first['maxtempF']
    self.button_min_temp_fahrenheit = temperature_bottom.first['mintempF']

    temperature_top = weather.first['top']
    self.top_max_temp = temperature_top.first['maxtempC']
    self.top_min_temp = temperature_top.first['mintempC']
    self.top_max_temp_fahrenheit = temperature_top.first['mintempF']
    self.top_min_temp_fahrenheit = temperature_top.first['mintempF']

    self.chance_of_snow = weather.first['chanceofsnow']
    self.total_snow_fall = weather.first['totalSnowfall_cm']
  end

  def request_weather_forecast
    url = "http://api.wunderground.com/api/f1189a1f5ed6a722/forecast10day/lang:en/q/#{latitude},#{longitude}.json"
    response = HTTParty.get(url)

    response = Hashie::Mash.new(response)
    forecast_days = response.forecast.txt_forecast.forecastday

    human_numbers = %w(zero one two three four five six)

    # For the next 7 days slice the day and night forecast and assing it to the index in human numbers 

    forecast_days[0..13].each_slice(2).each_with_index do  |(day, night), index|
      self.send("day_#{human_numbers[index]}_day_title=", day.title)
      self.send("day_#{human_numbers[index]}_day_text=", day.fcttext_metric)
      self.send("icon_day_#{human_numbers[index]}=", day.icon_url)
      self.send("day_#{human_numbers[index]}_night_title=", night.title)
      self.send("day_#{human_numbers[index]}_night_text=", night.fcttext_metric)
      self.send("icon_night_#{human_numbers[index]}=", night.icon_url)
    end
  end

  def updated_within_24_hours?
    self.updated_at > Time.now - 1.day
  end

end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  
  def index
    @q = Resort.search(params[:q])
    @all_resorts = @q.result(:distinct => true).order(:created_at)
    @resorts = @all_resorts.page(params[:page])
  end

  def location 
    @resorts = Resort.all
  end

  def show
    @resort = Resort.find_or_update(params[:id])
    @resort = Resort.request_weather(params[:id])
    @resort_region = Resort.find_or_update_region(params[:id])
    @comment = @resort.comments.new
  end

  def destroy
    @resort = Resort.find(params[:id])
    @resort.destroy
    redirect_to(resorts_path)
  end

  def like
    @resort = Resort.find(params[:id])
    @like = @resort.liked_by current_user 

    redirect_to @resort, notice: "Liked!"
  end

  def unlike
    @resort = Resort.find(params[:id])
    @unlike = @resort.downvote_from current_user

    redirect_to @resort, notice: "Unliked!"
  end

  def search_resorts
    @resorts = Resort.where("name ilike ?", "%#{params[:q]}%").select([:name, :id, :region])

    respond_to do |format|
      format.json { render :json => @resorts.map{|r| { name: r.name, id: r.id, region: r.region } } }
    end
  end


end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/views/resorts/_comment.html.haml
%h2 
  resort
  %span.magenta> review.
- if current_user
  #write_review
    .pure-form.pure-form-stacked.pure-form-aligned
      = form_for([@resort, @comment]) do |f|
        = f.text_area :comment, :size => "50x10", placeholder: "Add a Review..."
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :commentable_type, value: "Resort"
        %br
        = f.submit 'ADD REVIEW', :id => 'input_button_review', :class => 'pure-input-rounded'
- else
  %h2 
    Join us to review
    %span.magenta
      = @resort.name
    !
  %h1
    = link_to "register", new_user_registration_path
  
#comment_display
  - if @resort.comments.any?
    = render @resort.comments[0...@resort.comments.count]
  - else
    %h2
      Be the FIRST to review this resort

app/views/resorts/_like.html.haml
= link_to 'Like', resort_like_path(@resort), :method => :get, :remote => true

app/views/resorts/_map.html.haml
#map_canvas
  
- render 'shared/enable_map_js'

app/views/resorts/_total_likes.html.haml
= @resort.get_likes.size

app/views/resorts/_unlike.html.haml
= link_to 'Unlike', resort_unlike_path(@resort), :method => :get, :remote => true

app/views/resorts/_weather.html.haml
%h2
  = @resort.day_zero_day_title.downcase.strip
  %span.magenta> weather.
    

#weather_overview  
  .pure-g
    .pure-u-1-1
      %table
        %tr
          %th
            Today
          %th
            Tonight
          %th
            Snow
          %th
            Temperature
        %tr
          %td 
            = image_tag("#{@resort.icon_day_zero}")

          %td
            = image_tag("#{@resort.icon_night_zero}")
          %td
            %p
              Chances of Snow
            %h1
              = @resort.chance_of_snow
              \ %
          %td
            %p
              In the Valley
            %h1
              = @resort.button_min_temp 
              \ -
              = @resort.button_max_temp
              °C
            %strong
              = @resort.button_min_temp_fahrenheit
              \ -
              = @resort.button_max_temp_fahrenheit
              °F
        %tr
          %td 
            = @resort.day_zero_day_text

          %td
            = @resort.day_zero_night_text
          %td
            %p
              Total Snow Fall
            %h1
              = @resort.total_snow_fall
              cm
          %td
            %p
              On the Mountain
            %h1
              = @resort.top_min_temp
              \ -
              = @resort.top_max_temp
              °C
            %strong
              = @resort.top_min_temp_fahrenheit
              \ -
            %strong
              = @resort.top_max_temp_fahrenheit
              °F

%h3
  %span.black weekly
  %span.magenta> forecast.

#weather_forecast
  .pure-g
    .pure-u-1-6
      %p 
        = @resort.day_one_day_title
      = image_tag("#{@resort.icon_day_one}")
      = image_tag("#{@resort.icon_night_one}")

    .pure-u-1-6
      %p 
        = @resort.day_two_day_title
      = image_tag("#{@resort.icon_day_two}")
      = image_tag("#{@resort.icon_night_two}")

    .pure-u-1-6
      %p 
        = @resort.day_three_day_title
      = image_tag("#{@resort.icon_day_three}")
      = image_tag("#{@resort.icon_night_three}")

    .pure-u-1-6
      %p 
        = @resort.day_four_day_title
      = image_tag("#{@resort.icon_day_four}")
      = image_tag("#{@resort.icon_night_four}")

    .pure-u-1-6
      %p 
        = @resort.day_five_day_title
      = image_tag("#{@resort.icon_day_five}")
      = image_tag("#{@resort.icon_night_five}")

    .pure-u-1-6
      %p 
        = @resort.day_six_day_title
      = image_tag("#{@resort.icon_day_six}")
      = image_tag("#{@resort.icon_night_six}")
  

app/views/resorts/index.html.haml
#resort_index     
  %ul 
    - @resorts.each do |resort|
      %li 
        = image_tag(resort.map) if resort.map
        %h2
          = link_to resort.name, resort_path(resort)

    
    = paginate @resorts

app/views/resorts/location.html.haml
#location-overview
  = javascript_tag do
    window.resorts = #{raw @resorts.to_json}

  .map-show
    = render :partial => 'map'

app/views/resorts/show.html.haml
.resort_show
  %nav.L-1-1
    %ul.L-1-1
      %li
        %a#nav_one.L-3-12.gutters{href: "#one"} overview
      %li
        %a#nav_two.L-3-12.gutters{href: "#two"} reviews
      %li
        %a#nav_three.L-3-12.gutters{href: "#three"} weather
  %section#one.one.overview
    .overview-show
      %h1
        = @resort.name
      %p 
        = @resort_region.region
      %p 
        = link_to @resort.website, "#{@resort.website}"
      %p 
        = rating_for @resort, "resort", :star => 4
      - unless @resort.run_count.nil?
        %p
          Run Count:
          = @resort.run_count
      - unless @resort.lift_count.nil?
        %p
          Lift Count:
          = @resort.lift_count
      .pure-img
        = render :partial => 'map'
        = image_tag(@resort.map) if @resort.map

  %section#two.two.reviews
    .comment-show
      = render :partial => 'comment'

  %section#three.three.weather  
    .weather-show
      = render :partial => 'weather'



= javascript_tag do
  window.resorts = #{raw @resort.nearbys(50).to_json}
  window.resort = #{raw @resort.to_json} 






    

app/views/resorts/show.js.haml
- if current_user.liked? @resort
  var likesHTML = ("#{escape_javascript(render :partial => 'unlike')}");
- else current_user.disliked? @resort
  var likesHTML = ("#{escape_javascript(render :partial => 'like')}");

$(".like").html("#{escape_javascript(render :partial => 'total_likes')}");
$(".total_likes").html(likesHTML);