config/routes.rb
SkiApp::Application.routes.draw do

  get "home/index"

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resources :admins, only: [:index], as: 'admins'

  resources :home, only: [:index], as: '/' do
    get 'page/:page', action: :index, on: :collection
  end

  post '/rate' => 'rater#create', :as => 'rate'
  get '/resorts/location', to: "resorts#location", as: :resort_location
  get '/resort/:id/like', to: "resorts#like", as: :resort_like
  get '/resort/:id/unlike', to: "resorts#unlike", as: :resort_unlike
  get '/resorts/search_resorts', to: "resorts#search_resorts", as: :search_resorts

  resources :resorts do
    get 'page/:page', action: :index, on: :collection
    resources :comments do
      member do
        get 'inappropriate'
        delete 'delete_inappropriate', as: :delete_inappropriate
      end
    end
  end

  resources :users do
    resource :profile, only: [:show, :edit, :update]
  end

  root to: "home#index"

  

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title We Are
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %script{src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyA77x4_6dcnzuaQZfq5QvJcae6a72RMGTg&sensor=FALSE", type: "text/javascript"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .menu
      - if current_user
        #profile_pic_layout
          - if current_user.profile.profile_picture
            %img{src: current_user.profile.profile_picture.icon}
            %br
            %br
            %label
              hi,

        #logo_signed_in
          #sign_out
            = link_to image_tag('/assets/sign-out.png'), destroy_user_session_path, method: :delete, title: 'Sign Out', rel: 'data-tooltip'   
          %p
            = image_tag("/assets/logo.png")
            

          %ul
            %li
              = link_to 'search', "/"
            %li
              = link_to('resorts', resort_location_path)
            %li
              = link_to('my profile', user_profile_path(current_user))
            - if current_user.role == "admin"
              %li= link_to('admin panel', '/admins')
              
      - else
        #logo_signed_out
          = image_tag("/assets/logo.png")
        %ul
          %li
            = link_to "sign in", new_user_session_path
          %li
            = link_to "register", new_user_registration_path
          %li
            = link_to 'search', "/"
          %li
            = link_to('resorts', resort_location_path)
        


    
    .main_section 
      .login_alerts
        %p.notice= notice # Needed for Devise to alert User
        %p.alert= alert

      = yield

      = yield :map_javascript

    %footer
      %h2
        CONNECT WITH US

      .connect
        = link_to image_tag("/assets/twitter_2.png"), "https://twitter.com/share"
        = mail_to("paul_varga@me.com", image_tag("/assets/mail.png"))

      .privacy
        = render :partial => '/home/privacy'

      .rights
        © 2014 Paul Varga - All Rights Reserved